import { useState, useEffect } from 'react'
import { X, ExternalLink, Calendar, TrendingUp, FileText, Link as LinkIcon, AlertCircle, Download, Copy, Check } from 'lucide-react'
import axios from 'axios'
import { useToast } from './ToastProvider'
import RAGInsights from './RAGInsights'
import SuggestionList from './SuggestionList'

import ExportButton from './ExportButton'

function AnalysisModal({ itemId, onClose }) {
    const [data, setData] = useState(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(null)
    const [copied, setCopied] = useState(false)
    const toast = useToast()

    useEffect(() => {
        if (itemId) {
            fetchAnalysis()
        }

        const handleKeyDown = (e) => {
            if (e.key === 'Escape') onClose()
        }
        window.addEventListener('keydown', handleKeyDown)
        return () => window.removeEventListener('keydown', handleKeyDown)
    }, [itemId, onClose])

    const fetchAnalysis = async () => {
        try {
            setLoading(true)
            const response = await axios.get(`/api/analysis/${itemId}`)
            setData(response.data)
        } catch (err) {
            setError(err.response?.data?.detail || 'Failed to load analysis')
        } finally {
            setLoading(false)
        }
    }

    const getScoreColor = (score) => {
        if (score >= 70) return 'var(--success)'
        if (score >= 50) return 'var(--warning)'
        return 'var(--error)'
    }

    const handleCopyResults = () => {
        if (!data || !data.analysis) return

        const report = `
GEO VISIBILITY AUDIT REPORT
==========================
Target: ${data.title || 'N/A'}
URL: ${data.url || 'Direct Input'}
Engine: ${data.analysis.engine?.toUpperCase() || 'PERPLEXITY'}
Date: ${new Date(data.analysis.analyzed_at || data.created_at).toLocaleString()}

OVERALL GEO SCORE: ${data.analysis.overall_score}%

PILLAR SCORES:
- Structural Clarity: ${Math.round(data.analysis.structural_clarity_score)}%
- Citation Worthiness: ${Math.round(data.analysis.citation_worthiness_score)}%
- Semantic Coverage: ${Math.round(data.analysis.semantic_coverage_score)}%
- Freshness & Authority: ${Math.round(data.analysis.freshness_authority_score)}%

TOP RECOMMENDATIONS:
${Array.isArray(data.analysis.recommendations) ? data.analysis.recommendations.map(r => `* ${r}`).join('\n') : 'No recommendations available.'}

Generated by GEO Engine Optimizer
        `.trim()

        navigator.clipboard.writeText(report)
        setCopied(true)
        toast.success('Full report copied to clipboard!')
        setTimeout(() => setCopied(false), 2000)
    }

    if (!itemId) return null

    return (
        <div style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: 'var(--bg-primary)',
            opacity: 0.95,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 1000,
            padding: '2rem'
        }} onClick={onClose}>
            <div
                className="glass-card animate-fade-in"
                role="dialog"
                aria-modal="true"
                aria-labelledby="modal-title"
                style={{
                    width: '100%',
                    maxWidth: '900px',
                    maxHeight: '90vh',
                    overflow: 'auto',
                    padding: '2rem'
                }}
                onClick={(e) => e.stopPropagation()}
            >
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem' }}>
                    <div style={{ flex: 1 }}>
                        <h2 id="modal-title" style={{ fontSize: '1.5rem', fontWeight: '700', marginBottom: '0.25rem' }}>
                            {loading ? 'Loading...' : data?.title || 'Analysis Details'}
                        </h2>
                        {data?.analysis?.engine && (
                            <div style={{ marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.4rem', color: 'var(--text-tertiary)', fontSize: '0.75rem', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                                <Sparkles size={12} color="var(--accent-primary)" />
                                <span>Target: {
                                    data.analysis.engine === 'perplexity' ? 'Perplexity AI' : 
                                    data.analysis.engine === 'chatgpt' ? 'ChatGPT Search' : 
                                    data.analysis.engine === 'google_sge' ? 'Google SGE' : 
                                    data.analysis.engine
                                }</span>
                            </div>
                        )}
                        {data?.url && (
                            <a
                                href={data.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                style={{ color: 'var(--accent-primary)', fontSize: '0.875rem', display: 'flex', alignItems: 'center', gap: '0.25rem' }}
                            >
                                <ExternalLink size={14} /> {data.url}
                            </a>
                        )}
                    </div>
                    <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
                        {data && (
                            <>
                                <button
                                    onClick={handleCopyResults}
                                    title="Copy to clipboard"
                                    aria-label="Copy results to clipboard"
                                    style={{
                                        background: 'var(--bg-tertiary)',
                                        border: 'none',
                                        color: 'var(--text-secondary)',
                                        cursor: 'pointer',
                                        padding: '0.5rem',
                                        borderRadius: '6px',
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                        height: '38px'
                                    }}
                                >
                                    {copied ? <Check size={18} color="var(--success)" aria-hidden="true" /> : <Copy size={18} aria-hidden="true" />}
                                </button>
                                <ExportButton results={data.analysis || data} title={data.title} />
                            </>
                        )}
                        <button
                            onClick={onClose}
                            aria-label="Close modal"
                            style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', padding: '0.5rem' }}
                        >
                            <X size={24} aria-hidden="true" />
                        </button>
                    </div>
                </div>

                {loading && (
                    <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-secondary)' }}>
                        Loading analysis...
                    </div>
                )}

                {error && (
                    <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--error)' }}>
                        <AlertCircle size={48} style={{ marginBottom: '1rem', opacity: 0.5 }} />
                        <div>{error}</div>
                    </div>
                )}

                {data && !loading && !error && (
                    <>
                        {/* Score Cards */}
                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '1rem', marginBottom: '2rem' }}>
                            <div style={{ background: 'var(--bg-primary)', border: '1px solid var(--card-border)', borderRadius: '12px', padding: '1rem', textAlign: 'center', position: 'relative' }}>
                                <div style={{ fontSize: '2rem', fontWeight: '700', color: getScoreColor(data.analysis?.overall_score) }}>
                                    {data.analysis?.overall_score ?? 0}
                                </div>
                                <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>OVERALL</div>
                                {data.analysis?.score_delta !== undefined && (
                                    <div style={{ 
                                        position: 'absolute', 
                                        top: '-10px', 
                                        right: '-10px',
                                        background: data.analysis.score_delta >= 0 ? 'var(--success)' : 'var(--error)',
                                        color: 'white',
                                        fontSize: '0.65rem',
                                        padding: '2px 6px',
                                        borderRadius: '10px',
                                        fontWeight: 'bold',
                                        border: '2px solid var(--bg-primary)'
                                    }}>
                                        {data.analysis.score_delta >= 0 ? '+' : ''}{data.analysis.score_delta}
                                    </div>
                                )}
                            </div>
                            <div style={{ background: 'var(--bg-tertiary)', border: '1px solid var(--card-border)', borderRadius: '8px', padding: '0.75rem', textAlign: 'center' }}>
                                <div style={{ fontSize: '1.25rem', fontWeight: '600' }}>{Math.round(data.analysis?.structural_clarity_score ?? 0)}</div>
                                <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)' }}>AI Visibility</div>
                            </div>
                            <div style={{ background: 'var(--bg-tertiary)', border: '1px solid var(--card-border)', borderRadius: '8px', padding: '0.75rem', textAlign: 'center' }}>
                                <div style={{ fontSize: '1.25rem', fontWeight: '600' }}>{Math.round(data.analysis?.citation_worthiness_score ?? 0)}</div>
                                <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)' }}>Citation</div>
                            </div>
                            <div style={{ background: 'var(--bg-tertiary)', border: '1px solid var(--card-border)', borderRadius: '8px', padding: '0.75rem', textAlign: 'center' }}>
                                <div style={{ fontSize: '1.25rem', fontWeight: '600' }}>{Math.round(data.analysis?.semantic_coverage_score ?? 0)}</div>
                                <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)' }}>Semantic</div>
                            </div>
                            <div style={{ background: 'var(--bg-tertiary)', border: '1px solid var(--card-border)', borderRadius: '8px', padding: '0.75rem', textAlign: 'center' }}>
                                <div style={{ fontSize: '1.25rem', fontWeight: '600' }}>{Math.round(data.analysis?.freshness_authority_score ?? 0)}</div>
                                <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)' }}>Readability</div>
                            </div>
                        </div>

                        {/* Metadata & Progress */}
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
                            <div style={{ display: 'flex', gap: '1.5rem' }}>
                                <span style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                    <Calendar size={14} /> {new Date(data.created_at).toLocaleDateString()}
                                </span>
                                <span style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                    {data.url ? <LinkIcon size={14} /> : <FileText size={14} />}
                                    {data.url ? 'URL Analysis' : 'Text Analysis'}
                                </span>
                            </div>
                            
                            {data.analysis?.historical_trend?.length > 1 && (
                                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.4rem 0.8rem', background: 'var(--bg-tertiary)', borderRadius: '8px', border: '1px solid var(--card-border)' }}>
                                    <TrendingUp size={14} color="var(--accent-primary)" />
                                    <span style={{ fontSize: '0.75rem', fontWeight: '600' }}>History: {data.analysis.previous_analyses_count} audits</span>
                                    <div style={{ height: '20px', width: '60px', display: 'flex', alignItems: 'flex-end', gap: '2px' }}>
                                        {data.analysis.historical_trend.slice(-5).map((h, i) => (
                                            <div 
                                                key={i} 
                                                style={{ 
                                                    flex: 1, 
                                                    height: `${h.score}%`, 
                                                    background: 'var(--accent-primary)', 
                                                    opacity: 0.3 + (i * 0.15),
                                                    borderRadius: '1px' 
                                                }} 
                                                title={`${new Date(h.date).toLocaleDateString()}: ${Math.round(h.score)}%`}
                                            />
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>

                        {/* LLM Feedback */}
                        {data.analysis?.llm_feedback && (
                            <div style={{ marginBottom: '1.5rem' }}>
                                <h3 style={{ fontSize: '1rem', fontWeight: '600', marginBottom: '0.75rem' }}>AI Feedback</h3>
                                <div style={{
                                    background: 'var(--bg-tertiary)',
                                    border: '1px solid var(--card-border)',
                                    padding: '1rem',
                                    borderRadius: '8px',
                                    fontSize: '0.875rem',
                                    lineHeight: '1.6',
                                    color: 'var(--text-secondary)'
                                }}>
                                    {data.analysis.llm_feedback}
                                </div>
                            </div>
                        )}

                        {/* Recommendations */}
                        {data.analysis?.suggestions_detailed && data.analysis?.suggestions_detailed.length > 0 && (
                            <SuggestionList 
                                suggestions={data.analysis.suggestions_detailed}
                                contentItemId={data.id}
                                rawContent={data.analysis.raw_content || ""}
                            />
                        )}

                        {/* AI Strategic Insights */}
                        {(data.id || data.content_item_id) && (
                            <RAGInsights
                                contentItemId={data.id || data.content_item_id}
                                initialInsights={data.insights || []}
                            />
                        )}
                    </>
                )}
            </div>
        </div>
    )
}

export default AnalysisModal
